# Standards: 1.2
---
- name: Install required package
  action: "{{ ansible_pkg_mgr }} name={{ graylog_sidecar_package }} state=present disable_gpg_check=yes"
  tags:
    - graylog-sidecar

- name: Write config file
  notify:
    - Restart graylog-sidecar
  template:
    src: config.j2
    dest: /etc/graylog/sidecar/sidecar.yml
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - graylog-sidecar

- name: Write service file
  notify:
    - Restart graylog-sidecar
  template:
    src: service.j2
    dest: /etc/systemd/system/graylog-sidecar.service
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - graylog-sidecar

- name: Start graylog-sidecar service
  systemd:
    name: graylog-sidecar
    state: started
    daemon_reload: True
    masked: False
    enabled: True
  tags:
    - graylog-sidecar
